### ISSUE TITLE
Pushes are not being sent

### ISSUE THREAD

**Issue by RonMelkhior** [laravel-notification-channels/pushbullet#10]
Hello,

A question
1. Where am I supposed to add the `routeNotificationForPushbullet` method? In the `User` model? Or in the `Notification` class? From what I understand it needs to be in the `User` model, but when I try to do that I get:

```
 [ErrorException]
 Missing argument 1 for App\Notifications\GameVersionUpdate::toPushbullet(), called in ~PATH~\vendor\laravel-notification-channels\pushbullet\src\PushbulletChannel.php on line 49 and defined
```

The error does not happen if I attach the function to the `Notification` class, but then it doesn't send the notification at all.

Is there something I'm doing wrong?

**Comment by alexsoft** [comment]
@RonMelkhior hello
You are doing everything right. It's my fault that I do not pass the argument to `toPushbullet` method. Will fix it today or tomorrow. Sorry about that

**Comment by alexsoft** [comment]
@RonMelkhior fixed!
