### ISSUE TITLE
Send to own channel

### ISSUE THREAD

**Issue by wideivan** [laravel-notification-channels/pushbullet#11]
How about sending notes to own pushbullet channels?

**Comment by alexsoft** [comment]
@wideivan hi!
Are you talking about `channel_tag` parameter?

**Comment by wideivan** [comment]
@alexsoft Yes, I'm talking about `channel_tag` parameter (send the push to all subscribers to channel that has this tag) :-).

**Comment by alexsoft** [comment]
@wideivan okay, got it! will do my best to add it very soon.

**Comment by alexsoft** [comment]
@wideivan by the way, PRs are welcome 😉

**Comment by alexsoft** [comment]
@wideivan check out this commit 😉 
https://github.com/laravel-notification-channels/pushbullet/commit/177d496f645fb21323aa3b9c881ad238d980c199

**Comment by robinvalk** [comment]
Can a new version be tagged for this update? Changes are not showing up ^^

**Comment by alexsoft** [comment]
@robinvalk yeah, sure. Done!

**Comment by robinvalk** [comment]
Awesome thanks!
