### ISSUE TITLE
Laravel 5.5

### ISSUE THREAD

**Issue by omardavila64** [laravel-notification-channels/pushbullet#15]
Problem 1
    - Installation request for laravel-notification-channels/pushbullet ^0.2.0 -> satisfiable by laravel-notification-channels/pushbullet[v0.2.0].
    - Conclusion: remove laravel/framework v5.5.1
    - Conclusion: don't install laravel/framework v5.5.1
    - laravel-notification-channels/pushbullet v0.2.0 requires illuminate/notifications 5.3.*|5.4.* -> satisfiable by illuminate/notifications[v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - don't install illuminate/notifications v5.3.0|don't install laravel/framework v5.5.1
    - don't install illuminate/notifications v5.3.16|don't install laravel/framework v5.5.1
    - don't install illuminate/notifications v5.3.23|don't install laravel/framework v5.5.1
    - don't install illuminate/notifications v5.3.4|don't install laravel/framework v5.5.1
    - don't install illuminate/notifications v5.4.0|don't install laravel/framework v5.5.1
    - don't install illuminate/notifications v5.4.13|don't install laravel/framework v5.5.1
    - don't install illuminate/notifications v5.4.17|don't install laravel/framework v5.5.1
    - don't install illuminate/notifications v5.4.19|don't install laravel/framework v5.5.1
    - don't install illuminate/notifications v5.4.27|don't install laravel/framework v5.5.1
    - don't install illuminate/notifications v5.4.36|don't install laravel/framework v5.5.1
    - don't install illuminate/notifications v5.4.9|don't install laravel/framework v5.5.1
    - Installation request for laravel/framework (locked at v5.5.1, required as 5.5.*) -> satisfiable by laravel/framework[v5.5.1].

**Comment by alexsoft** [comment]
Should be good now. Just require 0.3 version

**Comment by omardavila64** [comment]
Thanks.
