### ISSUE TITLE
Ability to return user's api token from routeNotificationForPushbullet function would be nice

### ISSUE THREAD

**Issue by lauriek** [laravel-notification-channels/pushbullet#16]
At the moment this seems only usable for administrative notifications, as always pushbullet is instantiated by the service provider with a single API token from the env/config

It would be better IMO if the function which returns the routing info from the notifiable somehow returned an array of information including the API token, meaning each user could have their own API token and the site could notify users of stuff as well as admin..

(I do appreciate this is really an improvement request rather than an issue!)

**Comment by alexsoft** [comment]
I will investigate it asap and give make some decision. Thank you for feedback)

**Comment by Zerquix18** [comment]
I'm probably some years late but I could really benefit from this. Would you still accept a PR?

**Comment by atymic** [comment]
Hey @Zerquix18 and @alexsoft 

Maybe worth a PR?

**Comment by atymic** [comment]
cc @Zerquix18  :)

**Comment by alexsoft** [comment]
@lauriek @Zerquix18 you can just redefine api token in runtime, before sending notification.
`routeNotificationForPushbullet` in `Notifiable` is not the place to return api keys.
