### ISSUE TITLE
Cannot send to all devices

### ISSUE THREAD

**Issue by lauriek** [laravel-notification-channels/pushbullet#17]
Pushbullet has the ability to push notifications to all of a user's devices, if you simply do not supply an device_iden in the request. I can fudge this by commenting out one line in PushbulletMessage::toArray 

//'target' => $this->target->getTarget(),

And it then goes to all devices for the api token in the config. But it would be great if this was somehow an option without me having to hack about vendor code!!

**Comment by lauriek** [comment]
(Again I do appreciate this is technically a feature request rather than an issue!)

**Comment by alexsoft** [comment]
Again, I will see what I could do about it. Thanks)

**Comment by alexsoft** [comment]
@lauriek please check #38
